### ISSUE TITLE
Still fails to load occasionally on iOS 12.4, latest SafariPlus (1.7.6 or .7?)

### ISSUE THREAD

**Issue by badger200** [opa334/SafariPlus#25]
I read the changelog says this was fixed but it still happens to me probably 25% of the time when I reboot and jailbreak. 

iOS 12.4
iPad Pro 9.7”
Unc0ver 3.70b1
ALWAYS have >500 Tabs open, typically ~550.

Also yesterday I got a Communications Error for the first time ever, suggesting perhaps I had disabled SafariPlusSB.dylib in iCleaner Pro.  I checked because indeed I had recently disabled a bunch of tweaks to troubleshoot ~1x/daily random Springboard crashes, which didn’t happen a month ago when I was back on unc0ver 3.5.6..

However I verified that I had NOT disabled either of the 2 SafariPlus .dylibs. 

I’m able to workaround by force closing Safari and reopening, and if that doesn’t work, I just Respring then it’s fine. 

PS: I’ve never disabled Rocketbootstrap since basically everything seems to depend on it. But what version should I be on? Bc I recall months ago when I had electrarepo64.coolstar.org added (BAD IDEA), it updated my Rocketbootstrap from Beta3 to Beta5 if I recall correctly. It was 2 digits higher than what rpetrich.ch/repo was offering.

**Comment by opa334** [comment]
1.7.6 should have fixed the bug where Safari Plus occasionally does not load (at least according to my testers). The exact same problem that causes this was also able to trigger an incorrect "rocketbootstrap error" a while ago, but that should have been fixed in some 1.7 beta.

The rocketbootstrap error will appear when either rocketbootstrap is not working or SafariPlusSB.dylib is not injected into SpringBoard (this can also happen when not respringing after installing the tweak).

Just reinstalling rocketbootstrap should downgrade you back to the official version. Also try reinstalling Safari Plus while you're at it.

**Comment by badger200** [comment]
Haven’t had this issue in a long time. I think your reinstalling rocketbootstrap was the fix. Something probably got left over when I updated from 10.2.1 > 12.4 (yeah I’m a straggler lol)
