### ISSUE TITLE
BUG: Safari Reader no longer works on 1.7.17-3

### ISSUE THREAD

**Issue by lonkle** [opa334/SafariPlus#77]
Safari Reader no longer works after the latest SafariPlus update. Safari doesn’t Crash at all but I can’t use Reader anywhere without the screenshot attached error showing up immediately. 

- iPhone 12 mini, iOS 14.1, Taurine 1.0.5, SafariPlus 1.7.17-3

![image](https://user-images.githubusercontent.com/5572600/121509157-5c041600-c9b4-11eb-8982-8aa98bebde65.jpeg)

**Comment by opa334** [comment]
This error is shown if the WebContent XPC service crashes, the reason I knew Safari Plus wasn't causing this is because while SafariPlus does have a dylib injecting in WebContent, it's only used for getting the active video URL (for video downloading) and it can't really break reader mode. Anyways if it also happens in non jb mode then I presume some corrupted cache is causing this crash. Maybe try the "Clear History and Browsing Data" option in Settings under Safari.

**Comment by lonkle** [comment]
@opa334 Thank you for the lower-level explanation. I tried what you suggested but no dice. Tried a few more things, but this is just gonna be one of those "Restore rootFS" moments.

Thanks for your help, opa! ☺️

**Comment by lonkle** [comment]
Just wanted to add this to everyone out there. **Somehow** this was fixed by updating to Taurine 1.0.6 (I updated libhooker at the same time but that's not super relevant because the big existed in "jailed" mode). 

I wanted to document this and felt this was the best place to do so. 

Woo for not having to rootFS!
