### ISSUE TITLE
Does not compile with recent versions of WebKit

### ISSUE THREAD

**Issue by Lessica** [opa334/SafariPlus#85]
SafariPlus does not compile with recent versions of WebKit. But [WebKit Build Archives](https://webkit.org/build-archives/) only shows you latest nightly builds. To build this project, we have to find history version of precompiled WebKit.

I've made [this repo](https://github.com/Lessica/WebKitBuildArchives) to help you find earlier versions. For example, [WebKit@274758](https://s3-us-west-2.amazonaws.com/minified-archives.webkit.org/ios-simulator-14-x86_64-release/274758.zip) is a compatible version.

Another problem, uhh... Add `#import <UIKit/UIKit.h>` in a prefix header, please.

**Comment by opa334** [comment]
Yeah well this is too bad, I'm still using some ancient webkit version to compile this. I will check soon on how difficult it is to make newer versions work.

I'm not sure what you mean about the prefix header, the reason this right now doesn't compile for you is probably because of changes in how theos behaves when dealing with iOS 15 sdks, make sure you're using a 14.5 sdk from https://github.com/theos/sdks and it should compile. I probably won't do anything about this until a 15 jailbreak is out and I decide to port Safari Plus to iOS 15.

**Comment by opa334** [comment]
Nevermind, some recent theos commit changed things and the project indeed did no longer compiled, I have now adapted the Prefix.pch and it compiles again (thanks for the idea).

**Comment by opa334** [comment]
Okay it seems like it's impossible to use recent WebKit versions as they rely on stuff only available in iOS 11 and higher. I will therefore just add a script that downloads an old version and patches it on the fly.
